### ISSUE TITLE
Problem on ios when exit from screen and enter again

### ISSUE THREAD

**Issue by Darkmax** [juicycleff/flutter-unity-view-widget#148]
Hi I'm having a problem that is not present on android, only on ios devices. 

When the user exits (pop) the flutter screen where I have embeded the unity view this error pops up on the debug console

> Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel unity_view_0)

But everything apparently is working normal on flutter side, but the problem happens when the user enters for a second time where the flutter screen where the unity is embeded. If the user choose to exit again unity view flutter doesn't pop the screen.

The only tip that I have is that error that I mention first. Other user mention this same error before #107 and it was close because it @juicycleff mention that was fixed but this error still happens on the last version of the plugin.

So anyone has any idea on how to resolve this issue?

**Comment by PiotrxKolasinski** [comment]
Did you fix this problem?

**Comment by Darkmax** [comment]
Nope, I still have this problem on ios

**Comment by PiotrxKolasinski** [comment]
I'll try to resolve this problem today/tomorrow. If i find a solution, I'll write here :)

**Comment by Darkmax** [comment]
> I'll try to resolve this problem today/tomorrow. If i find a solution, I'll write here :)

Did you find a solution @PiotrxKolasinski of the bug?

**Comment by felixsmart** [comment]
Hi @PiotrxKolasinski same issue here!

Thanks for your help

**Comment by Darkmax** [comment]
Hi @PiotrxKolasinski, did you find what was the problem when exit the screen of unity and enter again and try again to exit, and the pop command of flutter doesn't work on ios?

**Comment by PiotrxKolasinski** [comment]
@Darkmax  sorry but i haven't found a solution yet

**Comment by samsgates** [comment]
anyone fix this issue?

**Comment by almeynman** [comment]
I think it should be fixed on master. I had a different issues, but noticed that dispose method of the controller got updated 5 days ago.

**Comment by samsgates** [comment]
i have used 3.0.1 (which is updated 5 days ago), but this problem still existed in IOS, (it's working fine in android). 
Problem : second time loading unity view is not working in IOS, this problem occurs when you 
- go back and come again to unity view
- go to home screen and come again to unity view

**Comment by almeynman** [comment]
Can you check if in Player setting under iOS tab "Render Extra Frame on Pause" is unchecked

**Comment by almeynman** [comment]
I don't have this issue on my project (running it on ios 14.2, Xcode 12.2 with flutter 1.24.0-6.0.pre) and on example app (tested example yesterday). Can you try these versions?

**Comment by samsgates** [comment]
"Render Extra Frame on pause" is already in unchecked mode. i am using xcode 12.1, unity 2020.4, IOS 13.1. let me check example app with your suggested version

**Comment by almeynman** [comment]
Or just try to run it with your versions and see if it is reproducable with example project

**Comment by samsgates** [comment]
i have tested with example app in IOS, please find the below result

Test :  go back and come again to unity view
Result : pass - working fine
Teset : go to home screen and come again to unity view
Result : fail - not working

Please find the video reference : https://youtu.be/meQXHpvHMOg

**Comment by almeynman** [comment]
oh, thanks for the video. I was misunderstanding the question. I reproduced the problem on the sample app. Got a bunch of errors in xcode log, will investigate and update you

**Comment by samsgates** [comment]
Thanks

**Comment by samsgates** [comment]
did you get any clue to fix it?

**Comment by almeynman** [comment]
@samsgates Hi, I inspected the errors I had, seems like they were related to a different issue. Do you have any errors in code when you come back from home screen?

**Comment by samsgates** [comment]
No, there is no error message appears in log. it's just not response from unitycontroller method. did you validate foreground and background callback from flutter-unity-widget code (objective-c code), because this issue not appear in android.

**Comment by samsgates** [comment]
did you fix it?

**Comment by khalithartmann** [comment]
have the same issue. any fix ?? @samsgates @almeynman @Darkmax

**Comment by chenenyu** [comment]
@juicycleff @almeynman @Darkmax @samsgates Any fix?? It's a terrible bug in my production...

**Comment by juicycleff** [comment]
Hello all, I'm looking to solve this problem, I tried reprising it on iOS but couldn't. Could you get a reproducible demo?

**Comment by chenenyu** [comment]
Page A(pure flutter page)  ----(push to)---> Page B(flutter page contains UnityWidget) ----(back to)----> Page A ----(push to)----> iPhone home screen ----(back to)---> Page A ----(push to)---> Page B

@juicycleff

**Comment by juicycleff** [comment]
@chenenyu i have done that but couldn't find the bug. If you can set up a demo project, would be great

**Comment by chenenyu** [comment]
> Build Setting - iOS - Other Settings - Configuration - Enable Custom Background Behaviors

This works for me.

**Comment by samsgates** [comment]
> > Build Setting - iOS - Other Settings - Configuration - Enable Custom Background Behaviors
> 
> This works for me.

This words for me as well. Thanks

**Comment by Darkmax** [comment]
> > Build Setting - iOS - Other Settings - Configuration - Enable Custom Background Behaviors
> 
> This works for me.

thanks this works for me

**Comment by nikiforospertselis** [comment]
I have the same issue on Android. Any solution?
