### ISSUE TITLE
A bug about repeat call stream to listen event

### ISSUE THREAD

**Issue by gneL1** [juicycleff/flutter-unity-view-widget#278]
**Describe the bug**  
&emsp;&emsp;because some reasons , I need to change the value of `enablePlaceholder` , and this value make me switch the state between `UnityWidget` and `placeholder`. and then , I got this bug ,due to switch state, `UnityWidget` is rebuilt and cause `onUnityMessage` repeat register.  

**To Reproduce**  
1. In this `UnityWidget` , i give `enablePlaceholder` with a variable.   

![github_I_ask_for_question_unity_03](https://user-images.githubusercontent.com/38184470/102453810-ef006b00-4077-11eb-8abf-609e857cd5dc.PNG)

&emsp;&emsp;by `setState()` to refresh the state between `UnityWidget` and `placeholder`.  
```dart
_show = !_show;
setState(() {
  
});
```

2. Now it is the first time to run project , `UnityWidget` build and call method `onPlatformViewCreated(int id) ` , current id is `0`.  
  
&emsp;&emsp;`flutter_unity_widget-3.0.1\lib\src\unity_view.dart`：  
![github_I_ask_for_question_unity_01](https://user-images.githubusercontent.com/38184470/102453802-ec057a80-4077-11eb-8792-6756c23d387d.PNG)

3. And In `controller.dart` , `_connectStreams` is called , `unityId` is set to `0` , method `onUnityMessage` is registed. Now if I pass value from `Unity` to `Flutter` , `onUnityMessage` will be called once.  
  
&emsp;&emsp;`flutter_unity_widget-3.0.1\lib\src\controller.dart`：  
![github_I_ask_for_question_unity_02](https://user-images.githubusercontent.com/38184470/102453807-edcf3e00-4077-11eb-9f32-083b97e3b37a.PNG) 

4. I change the value of `_show`, switch the state from `UnityWidget` to `placeholder` , that's OK. and then change the `_show` again, switch the state from `placeholder` to `UnityWidget`, `UnityWidget` is rebuilt , call method `onPlatformViewCreated(int id) `, we can see the `id` is `1` .  
![github_I_ask_for_question_unity_04](https://user-images.githubusercontent.com/38184470/102453811-ef990180-4077-11eb-95be-bdbc9a746991.PNG)

5. In `controller.dart` , `_connectStreams` is called , and `unityId` is `1` , method `onUnityMessage` is registed again!! Now I pass value from `Unity` to `Flutter` , `onUnityMessage` will be called twice .  
![github_I_ask_for_question_unity_05](https://user-images.githubusercontent.com/38184470/102453812-f0319800-4077-11eb-83b7-040a83fa8568.PNG)

**Summary**  
&emsp;&emsp;Every time `UnityWidget` is rebuilt , `onUnityMessage` is repeated registed , this need to be fixed.  
&emsp;&emsp;The reason I switch the state between `UnityWidget` and `placeholder ` , is that I need post a html url from `Unity` to `Flutter`, and `Flutter` open a new page by `Navigator.push` , in the new page is a `webview` to show url. if I don't hide `UnityWidget` , `UnityWidget` will cover `webview` in the new page.  
&emsp;&emsp;So every time I open a new page to show `webview` , set `enablePlaceholder` to true to hide `UnityWidget` , but now because the bug, `onUnityMessage` is called repeatedly.

**Comment by Eittipat** [comment]
Same behaviour but I did not set enablePlaceholder.

**Comment by juicycleff** [comment]
@Eittipat This has been fixed in v3.0.2. Please test and give your feedback

**Comment by songgravel** [comment]
> @Eittipat This has been fixed in v3.0.2. Please test and give your feedback

Hello, I have the same problem. Today I test _cancelSubscriptions in v3.0.2, it works well. 
But there is still a problem when I switch enablePlaceholder to show and hide UnityWidget. 
When I set enablePlaceholder to true, UnityWidget hides but it's dispose is not called, so the controller's dispose is not called. Then switch enablePlaceholder to false, the widget will be rebuilt, the _controller will complete again, and throw exception.

**Comment by gneL1** [comment]
> > @Eittipat This has been fixed in v3.0.2. Please test and give your feedback
> 
> Hello, I have the same problem. Today I test _cancelSubscriptions in v3.0.2, it works well.
> But there is still a problem when I switch enablePlaceholder to show and hide UnityWidget.
> When I set enablePlaceholder to true, UnityWidget hides but it's dispose is not called, so the controller's dispose is not called. Then switch enablePlaceholder to false, the widget will be rebuilt, the _controller will complete again, and throw exception.

yeah 3.0.2 still the problem , and I solve it by add `if(unityId != 0)return;` in `controller.dart`  
![2020_12_28](https://user-images.githubusercontent.com/38184470/103203185-5c8d8080-492f-11eb-8cff-ff5a22c0dbfa.PNG)
maybe my practice seems not so clever
