### ISSUE TITLE
Multithreaded Rendering turned on in Player Setttings crashes in UnityWidget.dispose on Android

### ISSUE THREAD

**Issue by mwelk** [juicycleff/flutter-unity-view-widget#299]
Disposing the UnityWidget leads to a crash on Android if "Multithreaded Rendering" is turned on in Unity Player Settings.

**To Reproduce**
1. Go back from stateless view with UnityWidget
2. See error
 
**Stacktrace**
```
E/Surface (14812): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -19
E/vulkan  (14812): dequeueBuffer failed: No such device (-19)
E/CRASH   (14812): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
E/CRASH   (14812): Version '2019.4.18f1 (3310a4d4f880)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
E/CRASH   (14812): Build fingerprint: 'google/coral/coral:11/RQ1A.210105.003/7005429:user/release-keys'
E/CRASH   (14812): Revision: 'MP1.0'
E/CRASH   (14812): ABI: 'arm64'
E/CRASH   (14812): Timestamp: 2021-01-18 16:06:42+0100
E/CRASH   (14812): pid: 14812, tid: 14997, name: UnityGfxDeviceW  >>> com.smeet.smeetng <<<
E/CRASH   (14812): uid: 10466
E/CRASH   (14812): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
E/CRASH   (14812): Cause: null pointer dereference
E/CRASH   (14812):     x0  0000000000000000  x1  0000007a8907b8f0  x2  0000000000000002  x3  0000000000000400
E/CRASH   (14812):     x4  0000000000000100  x5  0000000000000001  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
E/CRASH   (14812):     x8  00000079b0004df0  x9  00000000000001e7  x10 0000000000000010  x11 0000000000000000
E/CRASH   (14812):     x12 00000000000001ff  x13 000000000000002b  x14 00030239c0f26047  x15 0000000012100db6
E/CRASH   (14812):     x16 0000007a910ef950  x17 0000007dba788ce0  x18 0000007a8907b6b8  x19 00000079f0426e00
E/CRASH   (14812):     x20 00000079b0004df0  x21 00000079f0426e00  x22 0000000000000007  x23 00000079f0437bb8
E/CRASH   (14812):     x24 0000000000000001  x25 0000000000002713  x26 0000007a8907c000  x27 00000079f04269d0
E/CRASH   (14812):     x28 0000007980000388  x29 0000007a8907bbf0
E/CRASH   (14812):     sp  0000007a8907b8f0  lr  0000007a90792810  pc  0000007a90792830
E/CRASH   (14812): backtrace:
E/CRASH   (14812):       #00 pc 0000000000333830  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #01 pc 0000000000340610  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #02 pc 0000000000325134  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #03 pc 000000000057ad74  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #04 pc 0000000000581f84  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #05 pc 0000000000579210  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #06 pc 0000000000241300  /data/app/~~z1197YLab0tk0NCMRv-NFw==/com.smeet.smeetng-2H2kJcCtOP1kg8ftq2jBJw==/lib/arm64/libunity.so (BuildId: e4651a70790dd86978c70d3e8abbd59ace3182ea)
E/CRASH   (14812):       #07 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
E/CRASH   (14812):       #08 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```

**Expected behavior**
Release Unity resources on UnityWidget.dispose and re-initialize clean on new UnityWidget

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android 11
 - flutter-unity-view-widget: 3.0.2
 - Unity: 2019.4.18f1
- Flutter 1.22.5
- Dart 2.10.4

**Comment by mwelk** [comment]
Ok, the option "Multithreaded Rendering" in the Unity Player Settings must be turned off to get it working.

I will change the ticket to address this issue.

**Comment by juicycleff** [comment]
This has been fixed

**Comment by mrdavidrees** [comment]
@juicycleff Hey this still crashes for me even on 4.0.1+1. I still have to turn mutlithreading off to get this not to crash.

Is it something to do with loading up the app in unity 2019.4.16?
I know you're using a different version because Build.cs doesn't work in 2019.4.16 without this fix. (https://github.com/juicycleff/flutter-unity-view-widget/issues/234)
