### ISSUE TITLE
Execution failed for task ':unityLibrary:BuildIl2CppTask'.

### ISSUE THREAD

**Issue by joel-guti** [juicycleff/flutter-unity-view-widget#440]
Following all steps, when I try to compile from Flutter to a real Android device, I´m getting this error:

Total compilation time: 455873 milliseconds.
Error: Unity.IL2CPP.Building.BuilderFailedException: /Users/joel/Library/Android/sdk/ndk/23.0.7530507/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/n7/qdccy_41471d67w873834dtr0000gn/T/tmp48FuhM.tmp" -o "/Users/joel/Desktop/UNITY_FLUTTER/flutter_application_1/android/unityLibrary/build/il2cpp_armeabi-v7a_Release/il2cpp_cache/linkresult_957C279CD3368175BD29C9A69FA3072A/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target armv7-linux-androideabi19 -Wl,--wrap,sigaction "/Users/joel/Desktop/UNITY_FLUTTER/flutter_application_1/android/unityLibrary/src/main/jniStaticLibs/armeabi-v7a/baselib.a" -llog -rdynamic -fuse-ld=gold
clang-12: error: invalid linker name in argument '-fuse-ld=gold'
   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 363
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 160
   at il2cpp.Compilation.CompilationDriver.Run(RuntimePlatform platform, BuildingOptions buildingOptions, ReadOnlyCollection`1 matchedAssemblyMethodSourceFiles) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Compilation/CompilationDriver.cs:line 65
   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, BuildingOptions buildingOptions, Boolean throwExceptions) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Program.cs:line 74

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/joel/Desktop/UNITY_FLUTTER/flutter_application_1/android/unityLibrary/build.gradle' line: 52

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> Process 'command '/Users/joel/Desktop/UNITY_FLUTTER/flutter_application_1/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp'' finished with non-zero exit value 4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 56s
Exception: Gradle task assembleDebug failed with exit code 1

I´m getting the same result using Mac OS with Catalina and tested as well in Mac Os with Big Sur.

I have NDK installed, and I have disabled the mac security with:
sudo spctl --master-disable

Nothing works.

**Unity (please complete the following information):**
 - OS: [e.g. Android]
 - Version [e.g. 2020.3.f71]

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco X3
 - OS: 10 QKQ1

**Comment by samueltenoriosis** [comment]
same error, any solution?

**Comment by roberto-donext** [comment]
I found a solution that works for me. 
Looks that you can download a ndk version, but, Unity, by default is using it own version.
Check in Unity , Preferences / External Tools . Here you can find Android NDK installed with Unity.
The solution for me was, download NDK 19 from https://developer.android.com/ndk/downloads/older_releases
Go to the folder where Unity is using NDK, for example : 
/Applications/Unity/Hub/Editor/2020.3.15f2/PlaybackEngines/AndroidPlayer/NDK
Delete this content and replace with the new NDK downloaded.
Unity looks that only accept NDK version 19.0.5232133, so you can open the file source.properties in the new NDK folder and change the pkg.version with the accepted one:
Pkg.Revision = 19.0.5232133
Rememeber that you need to have the same version of NDK in two files more:
First on Android/local.properties:
ndk.dir=/Applications/Unity/Hub/Editor/2020.3.15f2/PlaybackEngines/AndroidPlayer/NDK for example
and on android/app/build.gradle:
ndkVersion "19.0.5232133"

With all this, I can compile for Android.
Hope this helps

**Comment by TaiTrien** [comment]
Hi guys,
I just fixed this problem by changing the version of NDK from 23 -> 19. You can find the version in Android Studio, choose Tools. -> SDK Manager -> Android SDK -> select SKD Tools tab -> click on Show package details checkbox -> then change the version of NDK. Good luck

**Comment by novavision** [comment]
I followed the steps @CodeMinion mentioned, and moved from that error to another :) 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripReleaseDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s
Running Gradle task 'assembleRelease'...                           81.7s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

What can it mean?

**Comment by DawidPietrykowski** [comment]
To anyone still facing this issue, in my case it was a flutter error. Currently the flutter snap package seems broken and installing it manually fixed the issue for me.

**Comment by jugbeep** [comment]
> I found a solution that works for me. Looks that you can download a ndk version, but, Unity, by default is using it own version. Check in Unity , Preferences / External Tools . Here you can find Android NDK installed with Unity. The solution for me was, download NDK 19 from https://developer.android.com/ndk/downloads/older_releases Go to the folder where Unity is using NDK, for example : /Applications/Unity/Hub/Editor/2020.3.15f2/PlaybackEngines/AndroidPlayer/NDK Delete this content and replace with the new NDK downloaded. Unity looks that only accept NDK version 19.0.5232133, so you can open the file source.properties in the new NDK folder and change the pkg.version with the accepted one: Pkg.Revision = 19.0.5232133 Rememeber that you need to have the same version of NDK in two files more: First on Android/local.properties: ndk.dir=/Applications/Unity/Hub/Editor/2020.3.15f2/PlaybackEngines/AndroidPlayer/NDK for example and on android/app/build.gradle: ndkVersion "19.0.5232133"
> 
> With all this, I can compile for Android. Hope this helps

I ensured the NDK referenced in my Flutter project's 'local.properties' file was pointing to the same NDK version used in Unity, and that solved it for me.

**Comment by ProEthan** [comment]
I found a solution that works for me.
Delete the unityLibrary folder in Android Project and re-copy-paste from Unity;

**Comment by Veerarma** [comment]
Hi, I tries all the above mentioned methods for this issue, none of them worked. Any more ideas ?

**Comment by arshad-dqot** [comment]
Open your unity project go to Edit->Preferences->ExternalTool and copy NDK path, Now open your flutter project local.properties and paste that path at ndk.dir

`sdk.dir=C:\\Users\\ThinkCentre4\\AppData\\Local\\Android\\sdk
ndk.dir=C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.9f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK
flutter.sdk=C:\\src\\flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1`

**Comment by arshad-dqot** [comment]
Open your unity project go to Edit->Preferences->ExternalTool and copy NDK path, Now open your flutter project local.properties and paste that path at ndk.dir

like this - `ndk.dir=C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.9f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK`

**Comment by sailinhtut** [comment]
> Open your unity project go to Edit->Preferences->ExternalTool and copy NDK path, Now open your flutter project local.properties and paste that path at ndk.dir
> 
> like this - `ndk.dir=C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.9f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK`

This work for me directly. Thank @arshad-dqot .

**Comment by Velek** [comment]
On March 29, 2023 2:01:28 AM PDT, Sai Lin Htut ***@***.***> wrote:
>> Open your unity project go to Edit->Preferences->ExternalTool and copy NDK path, Now open your flutter project local.properties and paste that path at ndk.dir
>> 
>> like this - `ndk.dir=C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.9f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK`
>
>This work for me directly. Thank @arshad-dqot .
>

I've been wondering if there it was likely to cause problems having Android Studio's SDK and tools and Unity's.
I just began changing part of a shipping app to Unity.
I keep having trouble with these lines the export adds in the unityLibrary/build.gradle file:
    buildToolsVersion '32.0.0'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

**Comment by AhmedNavaz** [comment]
> I found a solution that works for me. Delete the unityLibrary folder in Android Project and re-copy-paste from Unity;

This worked for me thanks.

**Comment by monkeyK1n9** [comment]
This other solution worked for me:
1- In Unity, go to Edit->Preferences->ExternalTool and copy NDK path,
2- Open from terminal ```cd <NDK path>```
3- open the source.properties file ```vi source.properties```
4- note the ndk version
5- add ```android {
    ndkVersion '<version>' ``` to your build.gradle in your unity/android/UnityLibrary
6- Create a file in your ```[Project root]/android/``` and name it local.properties
7- Copy the SDK and NDK path from Unity Edit->Preferences->ExternalTool. You should have something like this :
```
sdk.dir = <the path to sdk>
ndk.dir = <the path to ndk>
```
8- Now you can run the build again

**Comment by huzaifahazelGit** [comment]
> I found a solution that works for me. Looks that you can download a ndk version, but, Unity, by default is using it own version. Check in Unity , Preferences / External Tools . Here you can find Android NDK installed with Unity. The solution for me was, download NDK 19 from https://developer.android.com/ndk/downloads/older_releases Go to the folder where Unity is using NDK, for example : /Applications/Unity/Hub/Editor/2020.3.15f2/PlaybackEngines/AndroidPlayer/NDK Delete this content and replace with the new NDK downloaded. Unity looks that only accept NDK version 19.0.5232133, so you can open the file source.properties in the new NDK folder and change the pkg.version with the accepted one: Pkg.Revision = 19.0.5232133 Rememeber that you need to have the same version of NDK in two files more: First on Android/local.properties: ndk.dir=/Applications/Unity/Hub/Editor/2020.3.15f2/PlaybackEngines/AndroidPlayer/NDK for example and on android/app/build.gradle: ndkVersion "19.0.5232133"
> 
> With all this, I can compile for Android. Hope this helps

I have tried many ways to run simple unity android code but at last I am able to run the build properly good with ndkVersion 19.2.5345600
Nice Answering , Properly good working with 
sdk.dir=C\:\\Users\\huzai\\AppData\\Local\\Android\\Sdk
ndk.dir=C\:\\Users\\huzai\\AppData\\Local\\Android\\Sdk\\ndk\\19.2.5345600
