### ISSUE TITLE
Android Unity 2020.x freeze

### ISSUE THREAD

**Issue by sevantasci** [juicycleff/flutter-unity-view-widget#521]
Info: When i use Flutter Export with 2020.x.x it exports with the size of 90 KB version of unity-classes.jar. But when i export with 2019 it exports with the 100 KB version of unity-classes.jar which located in android/unityLibrary/libs/ 

Bug On 2020 build : After i build flutter. Unity starts fine with no problems. But when i remove Unity from screen and after when i call unity back, Unity totally freezes. Cant solve. Only solution i found manually changing unity-classes with 2019's unity-classes . It solves the problem but i think its not a good solution.
any help,solution will be great.

Thank you. :)

**Comment by sevantasci** [comment]
I tried with 3 different unity versions all has different unity-classes.jar. And all freezes why it is happening no one knows i really need help for this ? 
2021.2.8f
2019.4.34f
2020.3.26f

   switch (_selectedIndex) {
      case 0:
        return UnityDemoScreen();
      case 1:
        return Stack(
          children: [
            Container(
              height: MediaQuery.of(context).size.height,
              color: Colors.green,
            ),
          ],
        );
      case 2:
        return Container();
      default:
        return Container();
    }

when i return to case 0 it freezes.

**Comment by n00bsys0p** [comment]
We've had exactly this problem for the last week or 2, and ended up resolving it by adding some sketchy pause/resume code in a couple of places.

We did something like the following:

```dart
return UnityWidget(
  borderRadius: BorderRadius.zero,
  onUnityCreated: (UnityWidgetController controller) {
    _controller = controller;
    controller.pause().then((_) {
      controller.resume();
    });
  },
  onUnitySceneLoaded: (SceneLoaded? sceneInfo) {
    _controller.pause().then((_) {
      _controller.resume();
    });
  },
);
```

It needed both of these pause/resumes in order to fix the problem. It's also worth noting that the initial default scene does *not* seem to trigger `onUnitySceneLoaded`. We had to boot Unity into a "loader" scene and then tell it to load the proper scene in order to trigger it. Quite a complex and messy fix, but it works while there's no better solution.

**Comment by sevantasci** [comment]
Thank you for your answer @n00bsys0p . Yes its really not a good solution. I also tried same things but didn't work for me. I only found one solution and that is 100 KB version of unity-classes.jar and i don't remember which unity version is included with it. :(

**Comment by AkhilRaja** [comment]
@n00bsys0p confirming it's happening on iOS too.

**Comment by pavitter-bluestone** [comment]
I have the same problem with Unity2020.3.24f and Android. On IOS I'm currently having the #485 issue and cannot test it there.
I noticed, that unity is still running in the background correctly. When locking and unlocking the device after a "freeze" has occured, the Unity widgets starts to display the updated frames again.
Maybe it its some Platform View weirdness?

**Comment by AkhilRaja** [comment]
@n00bsys0p the random pause and resume and clearing ar sessions on every start fixed it for me. But unity starts with the previous ar session and takes a couple of frames to reload and that is visible.

**Comment by n00bsys0p** [comment]
@AkhilRaja Yeah - this is also happening to us when we use the pause-resume fix. We're going to try some things out to see if we can hack our way around it - maybe resetting to a blank scene before the UnityWidget is hidden or something.

**Comment by AkhilRaja** [comment]
> @AkhilRaja Yeah - this is also happening to us when we use the pause-resume fix. We're going to try some things out to see if we can hack our way around it - maybe resetting to a blank scene before the UnityWidget is hidden or something.

Yes please let me know if the blank scene before unloading from flutter works.

**Comment by sevantasci** [comment]
[unity-classes.zip](https://github.com/juicycleff/flutter-unity-view-widget/files/8002423/unity-classes.zip)
Changing unity-classes manually before build inside unityLibrary/libs with this version fixes on android.

**Comment by juicycleff** [comment]
This issue should have been fixed on both platforms in the latest releases

**Comment by juicycleff** [comment]
Please open the thread of you are still having this issue

**Comment by n00bsys0p** [comment]
@juicycleff Sorry to have to re-open the ticket - we're still having the problem on 4.2.5+1. It totally freezes the second time we return the UnityWidget from our Build method. It can be brought back to life by turning off the screen and turning it back on again as @pavitter-bluestone mentioned in https://github.com/juicycleff/flutter-unity-view-widget/issues/521#issuecomment-1028966273.

pubspec.yaml snippet:
```yaml
  flutter_unity_widget: ^4.2.5+1
```

pubspec.lock snippet (`grep -A3 flutter_unity_widget pubspec.lock`):
```yaml
  flutter_unity_widget:
    dependency: "direct main"
    description:
      name: flutter_unity_widget
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.5+1"
```

Process for building on MacOS:

```shell
cd /path/to/flutter-project

flutter clean

flutter pub get

rm -rf android/unityLibrary/

/Applications/Unity/Hub/Editor/2020.3.26f1/Unity.app/Contents/MacOS/Unity -batchmode -quit -projectPath /path/to/flutter-project/unity/UnityProject -logFile /dev/stdout -executeMethod Build.DoBuildAndroidLibrary -buildTarget Android
```

I then run the app on my device with `flutter run -d DEVICE_ID_HERE`.

The app logs don't seem to output anything useful at all that I can see. But you might be able to see something I can't. I've attached slightly sanitised (to remove sensitive data only) Flutter logs for 3 time periods. The first one is the time period during which the UnityWidget hangs, the second is during the process of locking the device, and the third is after unlocking the device again up to the point where the Unity widget started responding as normal (not including any of that stuff because I assume it's live by then).

When UnityWidget freezes:
```
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
V/PlayerBase( 8584): baseStart() piid=26263
W/pool-21-thread-( 8584): type=1400 audit(0.0:6852316): avc: denied { read } for pid=8584 name="u:object_r:kirin_audio_prop:s0" dev="tmpfs" ino=16425 scontext=u:r:untrusted_app:s0:c108,c259,c512,c768 tcontext=u:object_r:kirin_audio_prop:s0 tclass=file permissive=0
E/libc    ( 8584): Access denied finding property "persist.kirin.media.lowlatency.enable"
W/AudioTrack( 8584): createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 21202
V/AudioManager( 8584): querySoundEffectsEnabled...
W/pool-21-thread-( 8584): type=1400 audit(0.0:6852319): avc: denied { read } for pid=8584 name="u:object_r:kirin_audio_prop:s0" dev="tmpfs" ino=16425 scontext=u:r:untrusted_app:s0:c108,c259,c512,c768 tcontext=u:object_r:kirin_audio_prop:s0 tclass=file permissive=0
V/PlayerBase( 8584): baseStart() piid=26263
E/libc    ( 8584): Access denied finding property "persist.kirin.media.lowlatency.enable"
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
W/AudioTrack( 8584): createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 19491
W/libEGL  ( 8584): EGLNativeWindowType 0x6efb96a010 disconnect failed
D/mali_winsys( 8584): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys( 8584): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/AudioTrack( 8584): stop(4079): called with 491008 frames delivered
V/PlayerBase( 8584): baseStop() piid=26271
D/android.media.AudioTrack( 8584): [HSM] AudioTrace stop() uid: 10876, pid: 8584
V/PlayerBase( 8584): baseStop() piid=26271
V/PlayerBase( 8584): baseRelease() piid=26271 state=4
I/HwViewRootImpl( 8584): removeInvalidNode all the node in jank list is out of time
V/PlayerBase( 8584): baseRelease() piid=26271 state=0
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
```

After tapping the lock screen hardware button:
```
W/IInputConnectionWrapper( 8584): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 8584): getTextBeforeCursor on inactive InputConnection
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
I/HwViewRootImpl( 8584): removeInvalidNode all the node in jank list is out of time
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
W/libEGL  ( 8584): EGLNativeWindowType 0x6e994e8010 disconnect failed
W/BUNDLE_ID_HERE( 8584): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/BUNDLE_ID_HERE( 8584): NativeAlloc concurrent copying GC freed 2859(323KB) AllocSpace objects, 4(208KB) LOS objects, 49% free, 6794KB/13MB, paused 819us total 140.818ms
D/ZrHung.AppEyeUiProbe( 8584): not watching, wait.
W/libEGL  ( 8584): EGLNativeWindowType 0x6ee77eda90 disconnect failed
V/ActivityThread( 8584): Handle window ActivityRecord{b5c8ee3 token=android.os.BinderProxy@8831ffb {com.coinerz.triffic/com.coinerz.triffic.MainActivity}} visibility: false
```

After tapping the lock screen hardware button to unlock the screen - Unity widget comes up fine now, exactly as it should have:
```
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
I/chatty  ( 8584): uid=10876(BUNDLE_ID_HERE) identical 1 line
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
D/mali_winsys( 8584): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
D/ZrHung.AppEyeUiProbe( 8584): restart watching
D/SensorManager( 8584): 0x6f56bbd800 addFd fd=243
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
D/mali_winsys( 8584): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl( 8584): removeInvalidNode all the node in jank list is out of time
D/mali_winsys( 8584): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/BUNDLE_ID_HERE( 8584): NativeAlloc concurrent copying GC freed 24220(1340KB) AllocSpace objects, 20(912KB) LOS objects, 49% free, 6719KB/13MB, paused 1.941ms total 190.889ms
V/AudioManager( 8584): getStreamVolume streamType: 3 volume: 0
I/AudioTrack-JNI( 8584): AudioTrack_setup for usage=1 content=2 flags=0x0x800 tags=
```

**Comment by juicycleff** [comment]
What platform are you running on?

**Comment by n00bsys0p** [comment]
I'm exporting and compiling for Android, from MacOS Big Sur 11.6.2. I'm running the app on a Huawei P20 Pro with Android 10. I will also try this on a Samsung A12 running Android 11 and report back if it's the same.

**Comment by pavitter-bluestone** [comment]
4.2.5+1 doesnt fix the issue for me either.
I'm compiling for Android too, but from a Windows 10 Laptop. My App is running on an Samsung Tab S3 with Android 9.

**Comment by n00bsys0p** [comment]
Yeah, to confirm - we're using 2.5.3 as well.

**Comment by n00bsys0p** [comment]
I've just confirmed the exact same behaviour on Samsung Galaxy A12 with Android 11.

**Comment by n00bsys0p** [comment]
If it helps at all, here's an excerpt of our codebase where the issue occurs (we're using `flutter_bloc` for state management):

```dart
class GameOverlay extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => KiwiContainer().resolve<GameOverlayBloc>(),
        child: BlocBuilder<GameOverlayBloc, GameOverlayState>(
            builder: (BuildContext ctx, GameOverlayState state) {
          if (state is GameStartSuccess) {
            return UnityWidget(
              fullscreen: true,
              borderRadius: BorderRadius.zero,
              onUnityCreated: (UnityWidgetController controller) {
                BlocProvider.of<GameOverlayBloc>(ctx)
                    .add(GameStarted(controller));
              },
              onUnityMessage: (dynamic message) {
                if (message is String) {
                  BlocProvider.of<GameOverlayBloc>(ctx)
                      .add(GameMessageReceived(message));
                } else {
                  debugPrint(
                      "Unknown message: $message (${message.runtimeType.toString()})");
                }
              },
              onUnitySceneLoaded: (SceneLoaded? sceneInfo) {
                BlocProvider.of<GameOverlayBloc>(ctx)
                    .add(GameSceneLoaded(sceneInfo));
              },
            );
          } else {
            return LoadingWidget();
          }
        }));
  }
}
```

**Comment by sevantasci** [comment]
> [unity-classes.zip](https://github.com/juicycleff/flutter-unity-view-widget/files/8002423/unity-classes.zip) Changing unity-classes manually before build inside unityLibrary/libs with this version fixes on android. And on IOS i don't have any problems. I am using Unity version 2020.3.4f1

Yes issiue still continues. Its something about unity-classes.jar which only solution i found changing jar manually.  @juicycleff

**Comment by juicycleff** [comment]
@sevantasci yeah I don't quite have control of ver unity classes. As new versions comes, I just try to mitigate

**Comment by n00bsys0p** [comment]
Is there any way we can help you debug this issue @juicycleff? Our team can investigate whatever you might need to help you get to grips with it.

**Comment by juicycleff** [comment]
@n00bsys0p thanks but there is no need for that if you want to donate to https://opencollective.com/ultimate-backend. I'm currently trying to solve it at the moment.

**Comment by juicycleff** [comment]
This should suffice for now. One reason why keeping unity player in runtime always is hard is because of this change from aplicationcontext to activity context https://forum.unity.com/threads/problem-about-construct-unityplayer-with-applicationcontext-on-android.1165334/

**Comment by n00bsys0p** [comment]
@juicycleff I've implemented the latest version in our app and I'm afraid to say it hasn't helped at all. If anything, it's now less stable because calling an unload crashes the whole app.

I've managed to work around it all by putting in place an interstitial loader screen and some delays that seem to keep everything stable and consistent enough in our specific case, so it's not something that's urgent any more. But the core issue itself is still there.

If I get some time to do so I'll try and put together a minimal failing example for you to debug with.

**Comment by Altaf-jg** [comment]
Did anyone find any solution for this?
